name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'liberica'
          java-version: '17'
          architecture: 'x64'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Test with Maven
        run: mvn test --batch-mode

      - name: Build Docker image
        run: docker build . -t github-actions-demo

      - name: Login to Docker Hub
        run: |
          echo "Logging in to Docker Hub..."
          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
          echo "Login successful!"

      - name: Tag and Push Docker image
        run: |
          docker tag github-actions-demo ${{ secrets.DOCKER_HUB_USERNAME }}/github-actions-demo:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/github-actions-demo:latest